/** @format */

// app/layout.js
import { DarkModeProvider } from "@/src/context/DarkModeContext";
import "./globals.css"; // Your global CSS file

export const metadata = {
	title: "My Next.js App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<DarkModeProvider>{children}</DarkModeProvider>
			</body>
		</html>
	);
}
